name: 6 Jam

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading File Ngrok...
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Jksome/mengowkwo/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Jksome/mengowkwo/main/wallpaper.png -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githubusercontent.com/Jksome/mengowkwo/main/wallpaper.bat -OutFile wallpaper.bat
    - name: Ekstrak Ngrok File...
      run: Expand-Archive ngrok.zip
    - name: Menyambungkan ke Ngrok...
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Mengaktifkan RDP...
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Creating Tunnel...
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Sambungkan ke RDP Client
      run: cmd /c start.bat
    - name: RDP sedang berjalan...
      run: | 
        Invoke-WebRequest https://github.com/Jksome/mengowkwo/raw/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
